const APP_VERSION='1.0.0';
const DB_NAME='style-wishlist-db';
const DB_VERSION=1;
const TABS=['wishlist','purchased','wardrobe','more'];
const TAB_TITLES={wishlist:'Wishlist',purchased:'Acquistati',wardrobe:'Guardaroba',more:'Altro'};
const SEASONS=['Primavera','Estate','Autunno','Inverno'];
const CATEGORIES=['T-shirt','Felpa','Maglione','Camicia','Pantalone','Jeans','Giacca','Cappotto','Abito','Scarpe','Borsa','Accessorio','Altro'];
const state={tab:'wishlist',season:defaultSeason(),year:defaultYear(),filter:'Tutti',items:[],budgets:{},photoUrls:new Map(),draftPhotos:[],editingId:null};
const main=document.getElementById('main');
const sheet=document.getElementById('sheet');
const quickAdd=document.getElementById('quick-add');
const galleryInput=document.getElementById('gallery-input');
const cameraInput=document.getElementById('camera-input');
const backupInput=document.getElementById('backup-input');

function defaultSeason(){const m=new Date().getMonth()+1;if(m>=3&&m<=5)return'Primavera';if(m>=6&&m<=8)return'Estate';if(m>=9&&m<=11)return'Autunno';return'Inverno'}
function defaultYear(){const d=new Date();if(defaultSeason()==='Inverno'&&d.getMonth()+1>=10)return`${d.getFullYear()}/${String(d.getFullYear()+1).slice(-2)}`;return String(d.getFullYear())}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(n)||0)}
function id(){return 'i_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8)}
function toast(msg){document.querySelector('.toast')?.remove();const d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2600)}
function today(){return new Date().toISOString().slice(0,10)}
function fmtDate(s){if(!s)return'—';return new Date(s+'T12:00:00').toLocaleDateString('it-IT')}
function budgetKey(){return `${state.season}|${state.year}`}

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('items'))db.createObjectStore('items',{keyPath:'id'});if(!db.objectStoreNames.contains('photos'))db.createObjectStore('photos',{keyPath:'id'});if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function tx(store,mode,fn){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(store,mode),s=t.objectStore(store);let out;try{out=fn(s)}catch(e){reject(e);return}t.oncomplete=()=>resolve(out);t.onerror=()=>reject(t.error)})}
async function getAll(store){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function put(store,value){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(store,'readwrite'),r=t.objectStore(store).put(value);r.onsuccess=()=>resolve(value);r.onerror=()=>reject(r.error)})}
async function del(store,key){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(store,'readwrite'),r=t.objectStore(store).delete(key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function getOne(store,key){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(store).objectStore(store).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}

async function loadData(){state.items=await getAll('items');const settings=await getAll('settings');for(const s of settings){if(s.key==='budgets')state.budgets=s.value||{};if(s.key==='lastSelection'&&s.value){state.season=s.value.season||state.season;state.year=s.value.year||state.year}}render()}
async function saveSelection(){await put('settings',{key:'lastSelection',value:{season:state.season,year:state.year}})}
async function saveBudgets(){await put('settings',{key:'budgets',value:state.budgets})}

function revokePhotoUrls(){for(const url of state.photoUrls.values())URL.revokeObjectURL(url);state.photoUrls.clear()}
async function photoSrc(ref){if(!ref)return null;if(ref.type==='web')return ref.url;if(state.photoUrls.has(ref.id))return state.photoUrls.get(ref.id);const rec=await getOne('photos',ref.id);if(!rec?.blob)return null;const u=URL.createObjectURL(rec.blob);state.photoUrls.set(ref.id,u);return u}
async function firstPhotoSrc(item){return photoSrc(item.photos?.[0])}

function navRender(){document.getElementById('screen-title').textContent=TAB_TITLES[state.tab];document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));quickAdd.hidden=state.tab!=='wishlist'}
function seasonToolbar(){return `<div class="toolbar"><select id="season-select" class="grow">${SEASONS.map(s=>`<option ${s===state.season?'selected':''}>${s}</option>`).join('')}</select><input id="year-input" value="${esc(state.year)}" inputmode="text" aria-label="Anno o stagione" style="width:108px"></div>`}
function matchingSeason(item){return item.season===state.season&&item.year===state.year}
function wishlistItems(){return state.items.filter(i=>matchingSeason(i)&&['wishlist','ordered'].includes(i.status))}
function purchasedItems(){return state.items.filter(i=>i.status==='purchased').sort((a,b)=>(b.purchasedAt||'').localeCompare(a.purchasedAt||''))}
function wardrobeItems(){return state.items.filter(i=>i.status==='purchased'&&i.inWardrobe!==false).sort((a,b)=>(b.purchasedAt||'').localeCompare(a.purchasedAt||''))}
function filtered(items){if(state.filter==='Tutti')return items;if(state.filter==='Vestiti')return items.filter(i=>!['Scarpe','Borsa','Accessorio'].includes(i.category));if(state.filter==='Scarpe')return items.filter(i=>i.category==='Scarpe');if(state.filter==='Accessori')return items.filter(i=>['Borsa','Accessorio'].includes(i.category));if(state.filter==='Alta priorità')return items.filter(i=>i.priority==='Alta');if(state.filter==='Ordinati')return items.filter(i=>i.status==='ordered');return items}
function filterBar(){const arr=['Tutti','Vestiti','Scarpe','Accessori','Alta priorità','Ordinati'];return `<div class="filters">${arr.map(f=>`<button data-filter="${f}" class="${state.filter===f?'active':''}">${f}</button>`).join('')}</div>`}
function placeholderFor(item){return item.category==='Scarpe'?'👟':item.category==='Borsa'?'👜':item.category==='Accessorio'?'🕶️':'👕'}
function priorityClass(p){return p==='Alta'?'priority-high':p==='Media'?'priority-medium':'priority-low'}
function cardHtml(item){return `<article class="itemcard" data-item="${item.id}"><div class="thumb" data-thumb="${item.id}"><span class="placeholder">${placeholderFor(item)}</span></div><span class="badge ${priorityClass(item.priority)}">${esc(item.priority||'Media')}</span>${item.status==='ordered'?'<span class="statusbadge">Ordinato</span>':''}<div class="cardbody"><div class="itemtitle">${esc(item.name)}</div><div class="meta">${esc(item.brand||item.category||'')}</div><div class="price">${money(item.status==='purchased'?(item.paidPrice??item.expectedPrice):item.expectedPrice)}</div></div></article>`}
async function hydrateThumbs(root,items){for(const item of items){const box=root.querySelector(`[data-thumb="${CSS.escape(item.id)}"]`);if(!box)continue;const src=await firstPhotoSrc(item);if(src)box.innerHTML=`<img alt="${esc(item.name)}" src="${esc(src)}">`}}

async function renderWishlist(){const items=filtered(wishlistItems());const total=wishlistItems().reduce((s,i)=>s+(Number(i.expectedPrice)||0),0);const purchasedSeason=state.items.filter(i=>matchingSeason(i)&&i.status==='purchased').reduce((s,i)=>s+(Number(i.paidPrice)||Number(i.expectedPrice)||0),0);const budget=Number(state.budgets[budgetKey()]||0);main.innerHTML=`${seasonToolbar()}<div class="summary"><div class="metric"><small>Articoli</small><b>${wishlistItems().length}</b></div><div class="metric accent"><small>Wishlist</small><b>${money(total)}</b></div><div class="metric"><small>Acquistato</small><b>${money(purchasedSeason)}</b></div></div><div class="budgetcard"><div class="budgetrow"><div><span class="muted" style="font-size:11px">Budget ${esc(state.season)} ${esc(state.year)}</span><b>${budget?money(budget):'Non impostato'}</b></div><button class="ghostbtn small" id="edit-budget">Modifica</button></div>${budget?`<div class="progress"><span style="width:${Math.min(100,purchasedSeason/budget*100)}%"></span></div><div class="muted" style="font-size:11px;margin-top:7px">${money(purchasedSeason)} di ${money(budget)} utilizzati</div>`:''}</div>${filterBar()}${items.length?`<div class="grid">${items.map(cardHtml).join('')}</div>`:`<div class="empty"><div class="big">🛍️</div><b>Nessun articolo</b><div style="margin-top:6px">Aggiungi il primo capo, scarpa o accessorio per questa stagione.</div><button class="solidbtn" id="empty-add" style="margin-top:14px">Aggiungi articolo</button></div>`}`;bindCommonToolbar();main.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;render()});main.querySelector('#edit-budget')?.addEventListener('click',editBudget);main.querySelector('#empty-add')?.addEventListener('click',()=>openItemForm());main.querySelectorAll('[data-item]').forEach(c=>c.onclick=()=>openDetails(c.dataset.item));await hydrateThumbs(main,items)}
async function renderPurchased(){const items=purchasedItems();const total=items.reduce((s,i)=>s+(Number(i.paidPrice)||Number(i.expectedPrice)||0),0);main.innerHTML=`<div class="summary"><div class="metric"><small>Acquisti</small><b>${items.length}</b></div><div class="metric accent"><small>Speso</small><b>${money(total)}</b></div><div class="metric"><small>Guardaroba</small><b>${wardrobeItems().length}</b></div></div>${items.length?`<div class="grid">${items.map(cardHtml).join('')}</div>`:'<div class="empty"><div class="big">✓</div><b>Nessun acquisto registrato</b><div style="margin-top:6px">Gli articoli acquistati dalla wishlist compariranno qui.</div></div>'}`;main.querySelectorAll('[data-item]').forEach(c=>c.onclick=()=>openDetails(c.dataset.item));await hydrateThumbs(main,items)}
async function renderWardrobe(){const items=wardrobeItems();main.innerHTML=`<div class="toolbar"><select id="wardrobe-cat" class="grow"><option>Tutte le categorie</option>${CATEGORIES.map(c=>`<option>${c}</option>`).join('')}</select></div>${items.length?`<div class="grid">${items.map(cardHtml).join('')}</div>`:'<div class="empty"><div class="big">👔</div><b>Guardaroba vuoto</b><div style="margin-top:6px">Gli acquisti vengono aggiunti qui automaticamente.</div></div>'}`;const sel=main.querySelector('#wardrobe-cat');sel.onchange=async()=>{const f=sel.value==='Tutte le categorie'?items:items.filter(i=>i.category===sel.value);main.querySelector('.grid')?.remove();const e=main.querySelector('.empty');e?.remove();if(f.length){const g=document.createElement('div');g.className='grid';g.innerHTML=f.map(cardHtml).join('');main.appendChild(g);g.querySelectorAll('[data-item]').forEach(c=>c.onclick=()=>openDetails(c.dataset.item));await hydrateThumbs(g,f)}else main.insertAdjacentHTML('beforeend','<div class="empty">Nessun articolo in questa categoria.</div>')};main.querySelectorAll('[data-item]').forEach(c=>c.onclick=()=>openDetails(c.dataset.item));await hydrateThumbs(main,items)}
function renderMore(){main.innerHTML=`<div class="morecard"><h3>Backup dati</h3><p>Esporta tutti gli articoli, impostazioni e foto in un file JSON. Puoi poi ripristinarlo su un altro dispositivo.</p><div class="inline"><button class="solidbtn" id="export-backup">Esporta backup</button><button class="ghostbtn" id="import-backup">Importa</button></div></div><div class="morecard"><h3>Dati locali</h3><p>Style Wishlist salva i dati sul dispositivo tramite IndexedDB. Non richiede account o server.</p><button class="dangerbtn" id="clear-data">Cancella tutti i dati</button></div><div class="morecard"><h3>App</h3><p>Style Wishlist v${APP_VERSION}<br>Installabile da Safari tramite “Aggiungi a Home”.</p></div>`;main.querySelector('#export-backup').onclick=exportBackup;main.querySelector('#import-backup').onclick=()=>backupInput.click();main.querySelector('#clear-data').onclick=clearAllData}

async function render(){navRender();if(state.tab==='wishlist')await renderWishlist();if(state.tab==='purchased')await renderPurchased();if(state.tab==='wardrobe')await renderWardrobe();if(state.tab==='more')renderMore()}
function bindCommonToolbar(){main.querySelector('#season-select')?.addEventListener('change',async e=>{state.season=e.target.value;state.filter='Tutti';await saveSelection();render()});main.querySelector('#year-input')?.addEventListener('change',async e=>{state.year=e.target.value.trim()||defaultYear();state.filter='Tutti';await saveSelection();render()})}

function sheetOpen(html){if(sheet.open)sheet.close();sheet.innerHTML=`<div class="sheetinner">${html}</div>`;sheet.showModal()}
function sheetHead(title){return `<div class="sheethead"><h2>${esc(title)}</h2><button class="closebtn" data-close aria-label="Chiudi">✕</button></div>`}
function itemFormValues(item={}){return {name:item.name||'',category:item.category||'T-shirt',season:item.season||state.season,year:item.year||state.year,brand:item.brand||'',color:item.color||'',size:item.size||'',expectedPrice:item.expectedPrice??'',priority:item.priority||'Media',shop:item.shop||'',url:item.url||'',notes:item.notes||'',status:item.status||'wishlist'}}
async function openItemForm(item=null){state.editingId=item?.id||null;state.draftPhotos=(item?.photos||[]).map(x=>({...x}));const v=itemFormValues(item||{});sheetOpen(`${sheetHead(item?'Modifica articolo':'Nuovo articolo')}<form id="item-form"><div class="field full"><label>Foto</label><div class="photoactions"><button type="button" class="ghostbtn" id="take-photo">📷 Fotocamera</button><button type="button" class="ghostbtn" id="pick-photo">🖼️ Galleria</button><button type="button" class="ghostbtn" id="web-photo">🌐 Da web</button></div><div id="web-import" class="webrow" hidden><input id="web-url" type="url" placeholder="https://... immagine.jpg"><button type="button" class="solidbtn" id="add-web-url">Aggiungi</button></div><div class="photopreview" id="photo-preview"></div></div><div class="formgrid"><div class="field full"><label>Nome *</label><input name="name" value="${esc(v.name)}" required placeholder="Es. Cappotto lana"></div><div class="field"><label>Categoria *</label><select name="category">${CATEGORIES.map(c=>`<option ${c===v.category?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Priorità</label><select name="priority">${['Alta','Media','Bassa'].map(p=>`<option ${p===v.priority?'selected':''}>${p}</option>`).join('')}</select></div><div class="field"><label>Stagione</label><select name="season">${SEASONS.map(s=>`<option ${s===v.season?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>Anno</label><input name="year" value="${esc(v.year)}"></div><div class="field"><label>Marca</label><input name="brand" value="${esc(v.brand)}"></div><div class="field"><label>Colore</label><input name="color" value="${esc(v.color)}"></div><div class="field"><label>Taglia</label><input name="size" value="${esc(v.size)}"></div><div class="field"><label>Prezzo previsto €</label><input name="expectedPrice" type="number" step="0.01" inputmode="decimal" value="${esc(v.expectedPrice)}"></div><div class="field"><label>Negozio</label><input name="shop" value="${esc(v.shop)}"></div><div class="field full"><label>Link prodotto</label><input name="url" type="url" value="${esc(v.url)}" placeholder="https://..."></div><div class="field full"><label>Note</label><textarea name="notes" placeholder="Es. Aspettare i saldi">${esc(v.notes)}</textarea></div></div><div class="formactions"><button type="button" class="ghostbtn" data-close>Annulla</button><button type="submit" class="solidbtn">Salva</button></div></form>`);bindPhotoForm();sheet.querySelector('#item-form').onsubmit=saveItemFromForm;await renderPhotoPreview()}

function bindPhotoForm(){sheet.querySelector('#take-photo').onclick=()=>cameraInput.click();sheet.querySelector('#pick-photo').onclick=()=>galleryInput.click();sheet.querySelector('#web-photo').onclick=()=>{const r=sheet.querySelector('#web-import');r.hidden=!r.hidden};sheet.querySelector('#add-web-url').onclick=()=>{const input=sheet.querySelector('#web-url');const url=input.value.trim();if(!url)return;try{new URL(url)}catch{toast('URL immagine non valido');return}state.draftPhotos.push({type:'web',url});input.value='';renderPhotoPreview()}}
async function addFiles(files){for(const file of files){if(!file.type.startsWith('image/'))continue;const pid='p_'+id();await put('photos',{id:pid,blob:file,createdAt:new Date().toISOString()});state.draftPhotos.push({type:'local',id:pid})}await renderPhotoPreview()}
galleryInput.onchange=async()=>{await addFiles([...galleryInput.files]);galleryInput.value=''};cameraInput.onchange=async()=>{await addFiles([...cameraInput.files]);cameraInput.value=''};
async function renderPhotoPreview(){const root=sheet.querySelector('#photo-preview');if(!root)return;root.innerHTML='';for(let i=0;i<state.draftPhotos.length;i++){const ref=state.draftPhotos[i],src=await photoSrc(ref);const div=document.createElement('div');div.className='previewtile';div.innerHTML=src?`<img src="${esc(src)}" alt="Foto articolo"><button type="button" data-remove-photo="${i}">✕</button>`:`<span>Foto</span>`;root.appendChild(div)}root.querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=async()=>{const idx=Number(b.dataset.removePhoto),ref=state.draftPhotos[idx];state.draftPhotos.splice(idx,1);if(ref?.type==='local'&&!state.items.some(i=>i.photos?.some(p=>p.id===ref.id)))await del('photos',ref.id);renderPhotoPreview()})}
async function saveItemFromForm(e){e.preventDefault();const fd=new FormData(e.currentTarget),old=state.items.find(i=>i.id===state.editingId);const obj={id:old?.id||id(),name:String(fd.get('name')).trim(),category:String(fd.get('category')),season:String(fd.get('season')),year:String(fd.get('year')).trim()||defaultYear(),brand:String(fd.get('brand')).trim(),color:String(fd.get('color')).trim(),size:String(fd.get('size')).trim(),expectedPrice:Number(String(fd.get('expectedPrice')).replace(',','.'))||0,priority:String(fd.get('priority')),shop:String(fd.get('shop')).trim(),url:String(fd.get('url')).trim(),notes:String(fd.get('notes')).trim(),status:old?.status||'wishlist',paidPrice:old?.paidPrice??null,purchasedAt:old?.purchasedAt??null,inWardrobe:old?.inWardrobe??true,photos:state.draftPhotos.map(x=>({...x})),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!obj.name){toast('Inserisci il nome');return}await put('items',obj);state.items=state.items.filter(i=>i.id!==obj.id).concat(obj);sheet.close();toast(old?'Articolo aggiornato':'Articolo aggiunto');render()}

async function openDetails(itemId){const item=state.items.find(i=>i.id===itemId);if(!item)return;const src=await firstPhotoSrc(item);sheetOpen(`${sheetHead(item.name)}${src?`<img class="detailsphoto" src="${esc(src)}" alt="${esc(item.name)}">`:''}<div class="detailgrid"><div class="detailbox"><small>Categoria</small><b>${esc(item.category)}</b></div><div class="detailbox"><small>Stagione</small><b>${esc(item.season)} ${esc(item.year)}</b></div><div class="detailbox"><small>Marca</small><b>${esc(item.brand||'—')}</b></div><div class="detailbox"><small>Taglia</small><b>${esc(item.size||'—')}</b></div><div class="detailbox"><small>Colore</small><b>${esc(item.color||'—')}</b></div><div class="detailbox"><small>${item.status==='purchased'?'Pagato':'Prezzo previsto'}</small><b>${money(item.status==='purchased'?(item.paidPrice??item.expectedPrice):item.expectedPrice)}</b></div></div>${item.purchasedAt?`<div class="muted" style="font-size:12px;margin-bottom:10px">Acquistato il ${fmtDate(item.purchasedAt)}</div>`:''}${item.notes?`<div class="notes">${esc(item.notes)}</div>`:''}${item.url?`<a class="solidbtn" style="display:block;text-align:center;text-decoration:none;margin-top:10px" href="${esc(item.url)}" target="_blank" rel="noopener">Apri prodotto</a>`:''}<div class="detailactions"><button class="ghostbtn" id="edit-item">Modifica</button>${item.status==='wishlist'?'<button class="ghostbtn" id="mark-ordered">Segna ordinato</button>':''}${item.status!=='purchased'?'<button class="solidbtn full" id="mark-purchased">Segna acquistato</button>':`<button class="ghostbtn full" id="toggle-wardrobe">${item.inWardrobe===false?'Aggiungi al guardaroba':'Rimuovi dal guardaroba'}</button>`}<button class="dangerbtn full" id="delete-item">Elimina</button></div>`);sheet.querySelector('#edit-item').onclick=()=>openItemForm(item);sheet.querySelector('#mark-ordered')?.addEventListener('click',async()=>{item.status='ordered';item.updatedAt=new Date().toISOString();await put('items',item);sheet.close();render();toast('Articolo segnato come ordinato')});sheet.querySelector('#mark-purchased')?.addEventListener('click',()=>purchaseDialog(item));sheet.querySelector('#toggle-wardrobe')?.addEventListener('click',async()=>{item.inWardrobe=item.inWardrobe===false;await put('items',item);sheet.close();render()});sheet.querySelector('#delete-item').onclick=()=>deleteItem(item)}
function purchaseDialog(item){sheetOpen(`${sheetHead('Registra acquisto')}<form id="purchase-form"><div class="formgrid"><div class="field full"><label>Articolo</label><input value="${esc(item.name)}" disabled></div><div class="field"><label>Prezzo pagato €</label><input name="paid" type="number" step="0.01" inputmode="decimal" value="${esc(item.expectedPrice||'')}"></div><div class="field"><label>Data acquisto</label><input name="date" type="date" value="${today()}"></div><div class="field full"><label><input name="wardrobe" type="checkbox" checked style="width:auto;margin-right:8px">Aggiungi al guardaroba</label></div></div><div class="formactions"><button type="button" class="ghostbtn" data-close>Annulla</button><button class="solidbtn" type="submit">Conferma</button></div></form>`);sheet.querySelector('#purchase-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);item.status='purchased';item.paidPrice=Number(String(fd.get('paid')).replace(',','.'))||item.expectedPrice||0;item.purchasedAt=String(fd.get('date'))||today();item.inWardrobe=fd.get('wardrobe')==='on';item.updatedAt=new Date().toISOString();await put('items',item);sheet.close();toast('Acquisto registrato');render()}}
async function deleteItem(item){if(!confirm(`Eliminare “${item.name}”?`))return;await del('items',item.id);for(const ref of item.photos||[]){if(ref.type==='local'){const usedElsewhere=state.items.some(i=>i.id!==item.id&&i.photos?.some(p=>p.id===ref.id));if(!usedElsewhere)await del('photos',ref.id)}}state.items=state.items.filter(i=>i.id!==item.id);sheet.close();render();toast('Articolo eliminato')}
function editBudget(){const current=state.budgets[budgetKey()]||'';sheetOpen(`${sheetHead('Budget stagione')}<form id="budget-form"><div class="field"><label>Budget ${esc(state.season)} ${esc(state.year)} (€)</label><input name="budget" type="number" step="1" min="0" inputmode="decimal" value="${esc(current)}" placeholder="Es. 1000"></div><div class="formactions"><button type="button" class="ghostbtn" data-close>Annulla</button><button class="solidbtn">Salva</button></div></form>`);sheet.querySelector('#budget-form').onsubmit=async e=>{e.preventDefault();const n=Number(new FormData(e.currentTarget).get('budget'))||0;if(n>0)state.budgets[budgetKey()]=n;else delete state.budgets[budgetKey()];await saveBudgets();sheet.close();render()}}

async function blobToDataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
async function dataURLToBlob(data){const res=await fetch(data);return res.blob()}
async function exportBackup(){const photos=[];for(const rec of await getAll('photos'))photos.push({id:rec.id,data:await blobToDataURL(rec.blob),createdAt:rec.createdAt});const payload={app:'Style Wishlist',version:APP_VERSION,exportedAt:new Date().toISOString(),items:state.items,budgets:state.budgets,photos};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`style-wishlist-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
backupInput.onchange=async()=>{const file=backupInput.files?.[0];backupInput.value='';if(!file)return;try{const data=JSON.parse(await file.text());if(!Array.isArray(data.items))throw new Error('Formato non valido');if(!confirm('Importare il backup? I dati attuali verranno sostituiti.'))return;const db=await openDB();for(const store of ['items','photos','settings'])await new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).clear();t.oncomplete=res;t.onerror=()=>rej(t.error)});for(const item of data.items)await put('items',item);for(const p of data.photos||[])await put('photos',{id:p.id,blob:await dataURLToBlob(p.data),createdAt:p.createdAt});state.budgets=data.budgets||{};await saveBudgets();revokePhotoUrls();await loadData();toast('Backup importato')}catch(e){console.error(e);toast('Backup non valido')}}
async function clearAllData(){if(!confirm('Cancellare definitivamente tutti i dati di Style Wishlist?'))return;const db=await openDB();for(const store of ['items','photos','settings'])await new Promise((res,rej)=>{const t=db.transaction(store,'readwrite');t.objectStore(store).clear();t.oncomplete=res;t.onerror=()=>rej(t.error)});state.items=[];state.budgets={};revokePhotoUrls();render();toast('Dati cancellati')}

function switchTab(tab,dir=0){if(!TABS.includes(tab)||tab===state.tab)return;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const apply=()=>{state.tab=tab;state.filter='Tutti';window.scrollTo(0,0);render()};if(reduce||!main.animate){apply();return}const sign=dir||Math.sign(TABS.indexOf(tab)-TABS.indexOf(state.tab))||1;const out=main.animate([{transform:'translateX(0)',opacity:1},{transform:`translateX(${sign>0?'-18%':'18%'})`,opacity:.12}],{duration:130,easing:'ease-in',fill:'forwards'});out.finished.catch(()=>{}).finally(()=>{apply();main.animate([{transform:`translateX(${sign>0?'18%':'-18%'})`,opacity:.12},{transform:'translateX(0)',opacity:1}],{duration:190,easing:'cubic-bezier(.2,.75,.25,1)'});})}
let touch=null;main.addEventListener('touchstart',e=>{if(e.touches.length!==1||e.target.closest('button,input,select,textarea,a')){touch=null;return}touch={x:e.touches[0].clientX,y:e.touches[0].clientY}},{passive:true});main.addEventListener('touchend',e=>{if(!touch||!e.changedTouches.length)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;touch=null;if(Math.abs(dx)<65||Math.abs(dx)<Math.abs(dy)*1.3)return;const idx=TABS.indexOf(state.tab),next=(idx+(dx<0?1:-1)+TABS.length)%TABS.length;switchTab(TABS[next],dx<0?1:-1)},{passive:true});
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));quickAdd.onclick=()=>openItemForm();sheet.addEventListener('click',e=>{if(e.target===sheet||e.target.closest?.('[data-close]'))sheet.close()});

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=100').catch(console.error));
loadData().catch(e=>{console.error(e);main.innerHTML='<div class="empty">Errore durante il caricamento dei dati locali.</div>'});
